apiVersion: v1
kind: Pod
metadata:
  name: apione
  namespace: applicationservice
  labels:
    app: apione
spec:
  containers:
  - image: containerImageName
    name: apione-image
    ports:
    - containerPort: 80
      protocol: TCP
    imagePullPolicy: Always
  imagePullSecrets:
  - name: test
---
apiVersion: v1
kind: Service
metadata:
  name: apione-service
  namespace: applicationservice
spec:
  selector:
    app: apione
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reusableservice
  namespace: applicationservice
spec:
  type: ExternalName
  externalName: apitwo-service.reusableservice.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apione-service-ingress
  namespace: applicationservice
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: scanslips
spec:
  rules:
  - http:
      paths:
      - path: /api/washington/
        backend:
          serviceName: apione-service
          servicePort: 80
