---
- name: all
  hosts: localhost
  vars:
    appname: testjino
    file_location: /home/sepoy/Documents/ansible/webapp.zip
  tasks:
  - azureAccessToken:
      tenantid: "497833fc-c3cc-49c9-9c53-035cddc5fb08"
      clientid: "48e3e8d5-569f-462d-9d4b-fa6e8d3ea9a9"
      clientsecret: "5l~pb8xhfoDO.Ea7u91b2dbCLQuN5Ae2~V"
    register: _results
  - azurewebjobsdeploy:
      appServiceName: "{{ appname }}"
      accessToken: "{{  _results.meta.accessToken  }}"
      fileLocation: "{{ file_location }}"
