trigger: none

resources:
- repo: self

stages:
- stage: API_CREATION
  displayName: API_CREATION
  jobs:  
  - job: API_CREATION
    displayName: API_CREATION-ARM
    pool:
      vmImage: windows-latest
    steps:
    - task: AzureFileCopy@2
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: APIM
        azureSubscription: WbAdocredentials
        Destination: AzureBlob
        storage: wbapimstoragecontainer
        ContainerName: wbapimstoragecontainer
        BlobPrefix: wbapimstoragecontainer
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'APIM-API-CREATION'
      inputs:
        azureResourceManagerConnection: WbAdocredentials
        subscriptionId: 'a0808583-341e-4259-a7f8-10331546798f'
        resourceGroupName: 'wbg-poc'
        location: 'East US'
        csmFile: 'APIM/master.json'
        # csmFile: 'APIM/apis/apim-deploy.json'

# https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates